### PR TITLE
Avoid deleting block-level atoms with backspace

### PR DESCRIPTION
**Pull request by hubgit**
Pressing backspace at the start of a block which is after a block marked as an "atom" will delete the preceding block. This is undesirable, so this change prevents atomic blocks from being deleted with backspace (they will be selected, instead).

I'm not 100% sure of the side-effects of this change, so please advise if there might be a better alternative solution.

### CODE REVIEW

**Comment by marijnh** [comment]
This behavior was intentional. It may be undesirable to you, but just dropping it isn't something I'm interested in merging.

**Comment by hubgit** [comment]
Would `before.isAtom && !before.type.spec.isolating` be acceptable instead, so blocks marked as `isolating` would be protected from deletion in this way?

I can work around this by creating an `ignoreAtomBlockNodeBackward` backspace key handler, but it would be useful to know why the existing behaviour is intentional, as it feels like a bug when used in a document.

**Comment by marijnh** [comment]
I would suggest putting another command in front of `joinBackward` that detects this situation and does whatever you want to happen there.

**Comment by hubgit** [comment]
That's what I've ended up doing, yes - posted here for reference:

```js
// Copied from prosemirror-commands
const findCutBefore = ($pos) => {
  if (!$pos.parent.type.spec.isolating) {
    for (let i = $pos.depth - 1; i >= 0; i--) {
      if ($pos.index(i) > 0) return $pos.doc.resolve($pos.before(i + 1))
      if ($pos.node(i).type.spec.isolating) break
    }
  }
  return null
}

// Ignore atom blocks (as backspace handler), instead of deleting them.
// Adapted from selectNodeBackward in prosemirror-commands
export const ignoreAtomBlockNodeBackward = (state, dispatch, view) => {
  const { $cursor } = state.selection as TextSelection

  if (!$cursor) return false

  // ignore empty blocks
  if ($cursor.parent.content.size === 0) return false

  // handle cursor at start of textblock
  if (
    view ? !view.endOfTextblock('backward', state) : $cursor.parentOffset > 0
  ) {
    return false
  }

  const $cut = findCutBefore($cursor)

  if (!$cut) return false

  const node = $cut.nodeBefore

  if (!node) return false

  return node.isBlock && node.isAtom
}
```

**Pull request closed without merging**
